import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";


const regularFont = localFont({
  src: '../fonts/NeueHaasDisplay-Roman.woff2',
  weight: '400',
  style: 'normal',
  variable: "--font-rl"
})

const mediumFont = localFont({
  src: '../fonts/NeueHaasDisplay-Mediu.woff2',
  weight: '600',
  style: 'normal',
  variable: "--font-md"
})


export const metadata: Metadata = {
  title: "Modelo C 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${regularFont.variable} ${mediumFont.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
